### ISSUE TITLE
Analysis of the reports/dashboards/analytics

### ISSUE THREAD

**Issue by fcorti** [lcabaceira/crystal#10]
Which dashboards can/should be defined?
Which reports can/should be defined?
Which analytics can/should be defined?
About reports/analytics: how to release them in the crystal installation?

**Comment by fcorti** [comment]
The very first dashboard is an high view of the tests available.
Below an image of the committed version (few minutes ago).

<img width="1440" alt="schermata 2016-01-02 alle 19 42 13" src="https://cloud.githubusercontent.com/assets/6010860/12075699/f67fd628-b188-11e5-8708-b0d16c71bc77.png">

Now it's time to think about other dashboards, more detailed and dedicated to specific business questions.

**Comment by fcorti** [comment]
Added a dashboard that details the raw logs with filter on test and period (date only) and CSV/XLS export feature.

<img width="1440" alt="schermata 2016-01-04 alle 08 17 11" src="https://cloud.githubusercontent.com/assets/6010860/12085030/99c08926-b2bb-11e5-8422-af74ce5e76f6.png">

**Comment by lcabaceira** [comment]
Nice one, i'm going to give it a try later and provide feedback.

**Comment by lcabaceira** [comment]
I've updated both test cases (share automation and cmis tests) to generate reports on the correct folder and with the recommended pentaho friendly format.

**Comment by lcabaceira** [comment]
We should change the pentaho port to 9090 or other than 8080. People that is testing Crystal tend to have a local installation of Alfresco in 8080 and that conflicts with pentaho port. Is it just a matter of changing the tomat server.xml to listen on 9090 instead or we need to change it somewhere else ?

**Comment by fcorti** [comment]
No problem.
This week has been crazy in the office.
During the weekend I'll change the port and check the issues.

**Comment by fcorti** [comment]
Ok, Pentaho ports changed to 8080, 9009, 9443.
To answer to your question: yes, it is a matter to change the server.xml config file.

**Comment by lcabaceira** [comment]
You mean 9090,9009,9443 :) ?

**Comment by fcorti** [comment]
Ops... yes, 9090, 9009, 9443.
Updated also the documentation: https://github.com/lcabaceira/crystal/wiki

**Comment by lcabaceira** [comment]
The reports we need for now, that we already have inside jmeter and their data is already being exported are as follow : 

- Response times over time
- Transactions per second
- Active threads over time
- Hits per second
- Heap Memory
- Cpu Usage
- Garbage collector CMS (Collection Count/Collection Time)
- Garbage collector ParNew (Collection Count/Collection Time)
- Tomcat Threads HTTP (8080)
- Tomcat Threads HTTPS (8443)
- Tomcat Threads HTTPS (8009)
- Concurrent Users/Concurrent Tickets

I can attach the diagrams created by jmeter if those help.

**Comment by fcorti** [comment]
I'm going on this path...

Active threads over time is quite ready.
Response times over time is quite ready.

The others will come... stay tuned.

**Comment by fcorti** [comment]
Added the first draft of the reports below:
* Response times over time
* Transactions per second
* Active threads over time
* Hits per second

**Comment by fcorti** [comment]
ETL refined!
Now a TYPE field ha been added to the Data Mart and reports filter on this field.
Let's work on the other reports...

**Comment by fcorti** [comment]
All the available reports in JMeter are developed.
Of course need to be deeply tested.

![dashboard](https://cloud.githubusercontent.com/assets/6010860/12703979/c1a195d4-c850-11e5-8f43-8845cf2a20f7.png)
