### ISSUE TITLE
Analise CSV Files structure, defining dimensions and measures model 

### ISSUE THREAD

**Issue by lcabaceira** [lcabaceira/crystal#2]
Francesco to analise CSV files structure and provide feedback about enteties , model, structure of data-mart

**Comment by lcabaceira** [comment]
[francesco_csv.zip](https://github.com/lcabaceira/crystal/files/63022/francesco_csv.zip)

**Comment by fcorti** [comment]
I have found a good starting point.
http://alexandru-ersenie.com/2011/05/12/java-ee-load-performance-testing-and-reporting-using-open-source-tools-part-1-concept-examples-and-sample-reports/

We could be inspired for the first part of the project (the data structure and etl).
I don't know why but the author decided to use Jasper in a Pentaho environment... I would prefer to remain on the Pentaho path.

**Comment by lcabaceira** [comment]
Yes, that scripting part is really necessary. That was the part i was mentioning yesterday, when we use some remote scripting (mainly .sh or pearl scripts) to obtain infra-structure metrics during the tests execution. Those should also generate .csv files to feed the pentaho data extractor.

**Comment by fcorti** [comment]
Hi all,

Things are starting to become more clear.

According to the documentation page (http://wiki.apache.org/jmeter/LogAnalysis) all the report plugins should generate the same data structure (I'm quite sure but more checks will be done later).
For this reason we could base all the data migration to Pentaho on a single report extraction for each test (for example using a Simple Data Writer plugin).
Of course the users will be free to use a different plugin for interaction with Pentaho, or even define multiple plugins for her needs.

Saying that, the reasonable constraints I'm going to define are listed below:

- At least one report for each test case must be created. Feel free to choose type and name. If you don't have specific needs, a Simple Data Writer is recommended.

- Configure the report with the XML format ('Save As XML' flag) and as much as possibile flags selected.

- The filename must be defined as described below:

```${__BeanShell(import org.apache.jmeter.services.FileServer; FileServer.getFileServer().getBaseDir();)}${__BeanShell(File.separator,)}..${__BeanShell(File.separator,)}JMeterLogs${__BeanShell(File.separator,)}${__TestPlanName}_${__time(yyyy-MM-dd_HH-mm-ss,)}_${__UUID}.xml```

This string will instruct JMeter to save the report into the '<crystal>/TestCases/JMeterLogs' folder with the name '<ScriptName>_<date/time>_<UUID>.xml'.

Please share comments and suggestions if something should be defined differently.
I'm going to add this tutorial to the wiki.

**Comment by lcabaceira** [comment]
Looks good, i will change my cmis test to reflect that.
